# Generated by Django 4.2.3 on 2024-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0004_rename_room_message_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
