# Generated by Django 4.2.3 on 2024-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0005_message_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
