# Generated by Django 4.2.3 on 2024-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0006_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
