# Generated by Django 4.2.3 on 2024-04-29 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0007_alter_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='delete_hours',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
