# Generated by Django 4.2.3 on 2024-04-29 11:56

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0008_room_delete_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delete_hours',
            field=models.DateTimeField(default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(seconds=1800)))),
        ),
    ]
