# Generated by Django 4.2.3 on 2024-04-29 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0009_alter_room_delete_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delete_hours',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 12, 28, 7, 807134, tzinfo=datetime.timezone.utc)),
        ),
    ]
