# Generated by Django 4.2.3 on 2024-04-29 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0010_alter_room_delete_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delete_hours',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 12, 40, 53, 409458, tzinfo=datetime.timezone.utc)),
        ),
    ]
